[tool.poetry]
name = "soda-checks"
version = "0.1.0"
description = ""
authors = ["Nils JÃ¸rgen Mittet <nils.jorgen.mittet@nav.no>"]
license = "MIT"
readme = "README.md"
# packages = [{include = "soda_checks"}]

[tool.poetry.dependencies]
python = "^3.12"
soda-core-bigquery = "^3.0.47"
google-cloud-bigquery-storage = "^2.22.0"
pyarrow = "^17.0.0"
setuptools = "^75.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
