apiVersion: v1
kind: ConfigMap
metadata:
  name: soda-config
  namespace: helsearbeidsgiver
data:
  config.yaml: |
    data_source lps_api_dataset:
      type: bigquery
      connection:
      project_id: {{ gcp.project_id }}
      dataset: lps_api_dataset